language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: osx
      before_install:
        - brew install mariadb
        - brew services start mariadb
        - mkdir -p /usr/local/etc/my.cnf.d

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'billy'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - printf "[rs-dbi]\nusername=billy\npassword=supersecret\n" > ~/.my.cnf
